project_name: walship

builds:
  - id: walship
    main: ./cmd/walship
    binary: walship
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: tarball
    builds:
      - walship
    format: tar.gz
    name_template: "walship_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

dockers:
  - image_templates:
      - "ghcr.io/bft-labs/walship:{{ .Tag }}"
      - "ghcr.io/bft-labs/walship:latest"
    dockerfile: Dockerfile.goreleaser
    ids:
      - walship
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"

release:
  github:
    owner: bft-labs
    name: cosmos-analyzer-shipper
